Add new pages
saamerm/SMC-Website pull request #6
Opened 2024-04-04 18:11 UTC by hnucxr

1.Add pages "alt" value.
2.Added Arabic page, Dutch page, Spanish page.

2024-04-04 18:33 UTC, saamerm requested changes

2024-04-04 18:33 UTC, saamerm commented on index-zh.html
> +                                <a href="#" class="mn-has-sub"><i class="fa-solid fa-earth-americas"></i>English <i class="fa fa-angle-down"></i></a>
This should still be : 英文

2024-04-04 18:33 UTC, saamerm commented on index-nl.html
> +                            <a href="#" class="mn-has-sub"><i class="fa-solid fa-earth-americas"></i>English <i class="fa fa-angle-down"></i></a>
This should say Nederlands

2024-04-04 18:33 UTC, saamerm commented on index-ge.html
> -                            <a href="#" class="mn-has-sub"><i class="fa-solid fa-earth-americas"></i>Deutsche <i class="fa fa-angle-down"></i></a>
This should be Deutsche

2024-04-04 18:33 UTC, saamerm commented on index-fr.html
> -                            <a href="#" class="mn-has-sub"><i class="fa-solid fa-earth-americas"></i>Français <i class="fa fa-angle-down"></i></a>
This should still be : Français

2024-04-04 18:33 UTC, saamerm commented on index-es.html
> +                            <a href="#" class="mn-has-sub"><i class="fa-solid fa-earth-americas"></i>English <i class="fa fa-angle-down"></i></a>
This should be Español

2024-04-04 18:33 UTC, saamerm commented on index-ar.html
> +                            <a href="#" class="mn-has-sub"><i class="fa-solid fa-earth-americas"></i>English <i class="fa fa-angle-down"></i></a>
This should be العربيه

2024-04-04 18:54 UTC, hnucxr reviewed
update language

2024-04-05 01:40 UTC, saamerm approved these changes

2024-04-05 01:40 UTC, merged